from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from git_contribution_analyzer.domain.models.git_history import GitCommit, GitRef


class GitHistoryPort(Protocol):
    def list_refs(self) -> tuple[GitRef, ...]: ...

    def list_commit_hashes(self) -> tuple[str, ...]: ...

    def read_commits(self, commit_hashes: Iterable[str]) -> tuple[GitCommit, ...]: ...

    def reachable_commits(self, ref_name: str) -> frozenset[str]: ...

    def first_release_tags(self, commit_hashes: Iterable[str]) -> dict[str, str]: ...

    def is_ancestor(self, commit_hash: str, ref_name: str) -> bool: ...

    def tags_containing(self, commit_hash: str) -> tuple[str, ...]: ...
